name: yolov5_mm
channels: [conda-forge]          # only for Python & pip
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch                   # pulls latest 2.6-nightly +cu126
      - torchvision
      - torchaudio
      - -r requirements.txt
